version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server'
    restart: unless-stopped
    container_name: clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - IPC_LOCK
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
      - ./config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./initdb.d:/docker-entrypoint-initdb.d/
