version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecret
      MB_DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: metabase_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: metabase
    volumes:
      - ./metabase-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # <-- tambahkan baris ini
