version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    depends_on:
      - acme
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro

  acme:
    image: neilpang/acme.sh
    container_name: acme
    environment:
      - CF_Email=you@example.com         # ganti email kamu
      - CF_Token=YOUR_CLOUDFLARE_TOKEN   # jika pakai DNS Cloudflare
    command: daemon
    volumes:
      - ./acme:/acme.sh
      - ./certs:/certs
