version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: npm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: 12345
    volumes:
      - ./mysql:/var/lib/mysql

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: 12345
      DB_MYSQL_NAME: npm
      DISABLE_IPV6: 'true'
    depends_on:
      - db
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
