version: "3.8"

services:
  consul:
    image: hashicorp/consul:1.19
    container_name: consul
    restart: unless-stopped
    volumes:
      - ./consul-data:/consul/data
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui"

  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 0,
              "tls_cert_file": "/vault/config/certs/vault.crt",
              "tls_key_file": "/vault/config/certs/vault.key"
            }
          }],
          "storage": {
            "consul": {
              "address": "consul:8500",
              "path": "vault/"
            }
          },
          "ui": true,
          "cluster_name": "vault-prod"
        }
    volumes:
      - ./vault-config:/vault/config
      - ./certs:/vault/config/certs
    depends_on:
      - consul
