version: '3.8'

services:
  # ==========================================
  # 1️⃣ Reverse Proxy
  # ==========================================
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    networks:
      - proxy-tier

  # ==========================================
  # 2️⃣ Let's Encrypt (ACME Companion)
  # ==========================================
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=admin@games.com   # ubah ke email kamu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    networks:
      - proxy-tier

  # ==========================================
  # 3️⃣ Web (Nginx)
  # ==========================================
  web:
    image: nginx:latest
    container_name: web
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=web.games.com
      - LETSENCRYPT_HOST=web.games.com
      - LETSENCRYPT_EMAIL=admin@games.com
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-web
    networks:
      - proxy-tier

  # ==========================================
  # 4️⃣ PHP-FPM
  # ==========================================
  php-web:
    image: php:8.2-fpm
    container_name: php-web
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge
