version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: mydb
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
