version: "3"

services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata-parent
    hostname: netdata-parent
    restart: unless-stopped
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_parent_config:/etc/netdata
      - netdata_parent_lib:/var/lib/netdata
      - netdata_parent_cache:/var/cache/netdata
    environment:
      - NETDATA_PARENT=yes

volumes:
  netdata_parent_config:
  netdata_parent_lib:
  netdata_parent_cache:
